<script>
    import { onMount } from 'svelte';
    import { fade } from 'svelte/transition';
  
    // Datos del sitio web
    let logoRotation = 0;
    let phrases = ['Diseño arquitectónico', 'Planos para permisos', 'Administración de obra', 'Renders', 'Diseño de instalaciones (eléctrica e hidráulica)'];
    let currentPhrase = phrases[0];
    let visible = false;
    $: rota = logoRotation + 'deg';
      
    // Función para rotar el logo
    function rotateLogo() {
        logoRotation += 120;
        console.log(logoRotation);
    }
    
    // function spin(node, { duration }) {
    //   return {
    //     duration,
    //     css: t => {
    //       const eased = t;

    //       return (
    //         `transform: rotate(${eased * 120}deg);`
    //       )
    //     }
    //   };
    // }
  
    // Función para cambiar la frase
    function changePhrase() {
      const currentIndex = phrases.indexOf(currentPhrase);
      const nextIndex = (currentIndex + 1) % phrases.length;
      currentPhrase = phrases[nextIndex];
    }

    function aparece() {
      setTimeout(()=> { visible = false; },2500);
      setTimeout(()=> { visible = true; },500);
    };


  
    // Llamar a las funciones de forma recurrente
    onMount(() => {
        visible = true;
        setTimeout(()=> { visible = false; }, 2500);
        setInterval(aparece, 3000);
        setInterval(changePhrase, 3000); // Cambiar la frase cada 5 segundos
        // setInterval(spin, 3000); // Rotar el logo cada 3 segundos
        setInterval(rotateLogo, 3000); // Rotar el logo cada 3 segundos
    });
  </script>
  
  <style>
    /* Estilos para el cuerpo de la página */
    * {
        font-family: sans-serif;
    }
    body {
      margin: 0;
      border: none;
    }
    /* Estilos para las dos columnas */
    .row::after {
      content: "";
      clear: both;
      display: table;
    }
    .column {
      float: left;
      width: 33.33%;
      padding: 15px;
      box-sizing: border-box;
    }
    .column2 {
      float: left;
      width: 66.67%;
      padding: 15px;
      box-sizing: border-box;
      /* background-color: #4a4a4a; */
      color: antiquewhite;
      height: 100vh;
    }
    .color-change-3x {
      -webkit-animation: color-change-3x 9s infinite alternate both;
              animation: color-change-3x 9s infinite alternate both;
    }
    /* Estilos para el logo que gira */
    .logo {
      width: 150px;
      height: 150px;
      margin-bottom: 10px;
      transition: transform 2s;
    }
    /* Estilos para la frase dinámica que cambia */
    .phrase {
      color: antiquewhite;
      font-size: 18px;
    }
    /* Estilos para el diseño responsivo en pantallas pequeñas */
    @media screen and (max-width: 768px) {
      .column {
        width: 100%;
      }
      .column2 {
        height: auto;
      }
    }

    /* ----------------------------------------------
    * Generated by Animista on 2023-5-10 13:2:39
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info. 
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */

    /**
    * ----------------------------------------
    * animation color-change-3x
    * ----------------------------------------
    */
    @-webkit-keyframes color-change-3x {
      0% {
        background: #19dcea;
      }
      50% {
        background: #b22cff;
      }
      100% {
        background: #ea2222;
      }
    }
    @keyframes color-change-3x {
      0% {
        background: #19dcea;
      }
      50% {
        background: #b22cff;
      }
      100% {
        background: #ea2222;
      }
    }



  </style>
  
  <body>
    <div class="row">
      <div class="column">

        <img src="logo_aresdi_pt.png" style="transform:rotate({rota})" alt="Logo Aresdi" class="logo" id="logo">

        <p class="logo-text">ARESDI</p>
        <p style="margin-top: 160px;">Contacto:</p>
        <p>Teléfono: +1 123 456 7890</p>
        <p>Correo electrónico: info@example.com</p>
        <p>Dirección física: 123 Calle Principal, Ciudad, País</p>
      </div>
      <div class="column2 color-change-3x">
        {#if visible}
        <p class="phrase" id="phrase" transition:fade>{currentPhrase}</p>
        {/if}
      </div>
    </div>
  </body>
