<script>
    import { onMount } from 'svelte';
    import { fade } from 'svelte/transition';
  
    // Datos del sitio web
    let logoRotation = 0;
    let phrases = ['Diseño arquitectónico', 'Planos para permisos', 'Renders', 'Diseño de instalaciones (eléctrica e hidráulica)'];
    let currentPhrase = phrases[0];
    let visible = false;
    $: rota = logoRotation + 'deg';
      
    // Función para rotar el logo
    function rotateLogo() {
        logoRotation += 120;
        console.log(logoRotation);
    }
  
    // Función para cambiar la frase
    function changePhrase() {
      const currentIndex = phrases.indexOf(currentPhrase);
      const nextIndex = (currentIndex + 1) % phrases.length;
      currentPhrase = phrases[nextIndex];
    }

    function aparece() {
      setTimeout(()=> { visible = false; },2500);
      setTimeout(()=> { visible = true; },500);
    };
  
    // Llamar a las funciones de forma recurrente
    onMount(() => {
        visible = true;
        setTimeout(()=> { visible = false; }, 2500);
        setInterval(aparece, 3000);
        setInterval(changePhrase, 3000); // Cambiar la frase cada 3 segundos
        setInterval(rotateLogo, 3000); // Rotar el logo cada 3 segundos
    });
  </script>
  
  <style>
    /* Estilos para el cuerpo de la página */
    * {
        font-family: sans-serif;
        font-size: 1.24rem;
        line-height: 1.6rem;
        color:rgb(46, 47, 48);
    }
    a {
      color: unset;
    }
    body {
      margin: 0 !important;
      border: none;
    }

    /* Estilos para las dos columnas */
    .row::after {
      content: "";
      clear: both;
      display: block;
    }
    .row {
      height: 100vh;
      display: flex;
      flex-direction: column;
      flex-wrap: wrap;
    }
    .column {
      display: flex;
      flex-direction: column;
      max-width: 240px;
      padding: 22px;
      margin: 36px 0 36px 36px;
      box-sizing: border-box;
      border-radius: 18px;
      background: rgba(255,255,255,0.25);
      box-shadow:  6px 6px 16px rgba(205, 205, 205, 0.5),
                  -6px -6px 16px rgba(255, 255, 255, 0.5);
    }
    .column2 {
      float: left;
      padding: 15px;
      box-sizing: border-box;
      /* background-color: #4a4a4a; */
      color: antiquewhite;
      height: 100vh;
    }
    .color-change-3x {
      -webkit-animation: color-change-3x 9s infinite alternate both;
              animation: color-change-3x 9s infinite alternate both;
    }
    /* Estilos para el logo que gira */
    .logo {
      width: 114px;
      height: 114px;
      margin: auto;
      padding: 28px;
      transition: transform 2s;
      align-items: center;
      justify-content: center;
    }
    .logo-text {
      font-weight: bolder;
      font-size: 2rem;
      letter-spacing: 0.3rem;
      color: rgb(46, 47, 48);
      margin: 0 auto 52px auto;
    }
    .mailto {
      margin-bottom: 1rem;
    }
    /* Estilos para la frase dinámica que cambia */
    .phrase {
      color: antiquewhite;
      font-size: 1.7rem;
    }
    /* Estilos para el diseño responsivo en pantallas pequeñas */
    @media screen and (max-width: 768px) {
      .column {
        width: 100%;
      }
      .column2 {
        height: auto;
      }
    }

    /* ----------------------------------------------
    * Generated by Animista on 2023-5-10 13:2:39
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info. 
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */

    /**
    * ----------------------------------------
    * animation color-change-3x
    * ----------------------------------------
    */
    @-webkit-keyframes color-change-3x {
      0% {
        background: #4fc8d1;
      }
      50% {
        background: #ce8bf5;
      }
      100% {
        background: #f57e7e;
      }
    }
    @keyframes color-change-3x {
      0% {
        background: #4fc8d1;
      }
      50% {
        background: #ce8bf5;
      }
      100% {
        background: #f57e7e;
      }
    }

  </style>
  
  <body>
    <div class="row color-change-3x">
      <div class="column">

        <img src="logo_aresdi_pt.png" style="transform:rotate({rota})" alt="Logo Aresdi" class="logo" id="logo">

        <div class="logo-text">ARESDI</div>
        <div class="mailto">
          <a href="mailto:contacto@aresdi.com">contacto@aresdi.com</a>
        </div>
        <a aria-label="Chat on WhatsApp" href="https://wa.me/525517742133?text=Hola%20aresdi,%20quisiera%20ayuda%20con%20mi%20proyecto%20de%20">
          <img alt="Chat on WhatsApp" width="168px" src="WhatsAppButtonWhiteSmall.png" />
        </a>
        <p>San Miguel de Allende, Gto. México</p>
      </div>
      <div class="column2 color-change-3x">
        {#if visible}
        <p class="phrase" id="phrase" transition:fade>{currentPhrase}</p>
        {/if}
      </div>
    </div>
  </body>
